Set up associations
FilbertKimasa/School-library pull request #3
Opened 2023-11-23 11:41 UTC by FilbertKimasa

**In this PR the following was done:**

- [ ] Create a class Classroom
- [ ] Create the has-many/belongs-to relationship between Classroom and Student
- [ ] Create a class Book
- [ ] Create a class Rental
- [ ] Create the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental

2023-11-23 13:54 UTC, OyePriscilla requested changes
Hi @FilbertKimasa , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Set up associations between classes and objects. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-23 13:54 UTC, OyePriscilla commented on book.rb
> +  end
- [ ] Kindly implement a method for adding rentals that should be present as stated in the requirement. ℹ️ 

<img width="632" alt="Untitled" src="https://github.com/FilbertKimasa/School-library/assets/103386183/b6c43e71-2e11-4550-9353-3ee854535cdc">

Suggestion
```
def add_rental(person, date)
    Rental.new(date, self, person)
  end
```

2023-11-23 13:54 UTC, OyePriscilla commented on person.rb
>    end
- [ ] Kindly implement a method for adding rentals that should be present as stated in the requirement. ℹ️ 
- [ ] There sholud be `*Getters and Setters for @rentals (attr_accessor)` **`not Getters (attr_reader)`** as you implemented.

<img width="632" alt="Untitled" src="https://github.com/FilbertKimasa/School-library/assets/103386183/e691dd57-dc59-488d-837e-b16aca74baee">

2023-11-23 13:54 UTC, OyePriscilla commented on classroom.rb
> +  end
- [ ] There sholud be `*Getters method for @students (attr_reader)` **`not Getters and Setters method (attr_accessor)`** as you implemented.

2023-11-23 13:54 UTC, OyePriscilla commented on student.rb
> +
- [ ]  There sholud be *Getters method for @classroom (attr_reader) not Getters and Setters method (attr_accessor) as you implemented.

2023-11-23 13:54 UTC, OyePriscilla commented on student.rb
> +    # classroom&.students&.push(self)
- [ ] Kindly remove this commented code in order for your codebase to be clean. ℹ️

2023-11-24 14:47 UTC, mukhammadrizooff requested changes
Hi @FilbertKimasa, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 14:47 UTC, mukhammadrizooff commented on book.rb
> +  end
- [ ] [REQUIRED] Good job so far! Please implement the [previous reviewer's suggestion](https://github.com/FilbertKimasa/School-library/pull/3/files#r1403391439), kindly implement the `many-to-many` relationship between Person and Book using the intermediate class `Rental` 🙏🏼 

```ruby
  def add_rental(person, date)
    # *the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. 
    Rental.new(date, self, person)
  end
```

2023-12-01 05:22 UTC, topeogunleye requested changes
Hi @FilbertKimasa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
Great job, Filbert! 🌟 You've successfully implemented the required features for the Classroom, Student, Book, and Rental classes. Here are the highlights:

#### Classroom Class

1. **Getter and Setter for `@label`:**
   - You have correctly implemented the `attr_accessor :label` for the `@label` instance variable, allowing seamless access.

2. **Initialization in Constructor:**
   - The `initialize` method correctly initializes the `@label` instance variable, following the principles of constructors.

3. **Has-Many Relationship (Classroom has Many Students):**
   - The `add_student` method establishes the 'has-many' relationship, adding a student to the classroom and setting the classroom for the student.

#### Student Class

1. **Getter and Setter for `@classroom`:**
   - The `attr_reader :classroom` and the `classroom=` method ensure proper encapsulation and access to the `@classroom` instance variable.

2. **Belongs-To Relationship (Student belongs to Classroom):**
   - The `classroom=` method establishes the 'belongs-to' relationship, setting the classroom for a student and adding the student to the classroom's students.

#### Book Class

1. **Getters and Setters for `@title` and `@author`:**
   - The `attr_accessor` ensures that both `@title` and `@author` have appropriate getters and setters.

2. **Initialization in Constructor:**
   - The `initialize` method correctly initializes the `@title` and `@author` instance variables.

#### Rental Class

1. **Getter and Setter for `@date`:**
   - You have successfully implemented the `attr_accessor :date` for the `@date` instance variable.

2. **Initialization in Constructor:**
   - The `initialize` method initializes the `@date` instance variable, adhering to constructor principles.

Your implementation aligns well with the specified requirements. Keep up the excellent work! If you have any questions or need further guidance, feel free to ask. 🚀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 05:22 UTC, topeogunleye commented on book.rb
> +  end
Hey there! 👋🏼 Great progress on your code! 🚀 Just a gentle reminder to implement the many-to-many relationship between Person and Book using the intermediate class Rental. 📚💼 Utilizing the Rental class for this association will enhance the structure. You got this! 🌟👩‍💻 #CodeImprovement #KeepCoding #CodeReviewFeedback 🙏🏼

### A book has many rentals

## EXAMPLE:

```.rb
  # *A method for adding rentals should be present. Link to the example in a previous lesson: https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship
  def add_rental(person, date)
    # *the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. 
    Rental.new(date, self, person)
  end

```

2023-12-01 05:22 UTC, topeogunleye commented on student.rb
> +  end
[OPTIONAL]
Your code is on the right track for establishing a 'belongs-to' relationship between a student and a classroom. However, there's a more conventional way to achieve this while also ensuring data consistency. Instead of the `add_to_classroom` method, consider using the `classroom=` method. This method not only sets the classroom for the student but also updates the classroom's list of students.

Here's a suggestion:

```ruby
def classroom=(classroom)
  @classroom = classroom
  classroom.students.push(self) unless classroom.students.include?(self)
end
```

This way, you're not just setting the classroom for the student but also maintaining the relationship from the classroom's perspective. Keep up the good work! 🚀👩‍💻 #CodeReview #ObjectOrientedProgramming #KeepRefining 🌟

2023-12-01 05:22 UTC, topeogunleye commented on person.rb
Hey there! 👋🏼 Great progress on your code! 🚀 Just a gentle reminder to implement the many-to-many relationship between Person and Book using the intermediate class Rental. 📚💼 Utilizing the Rental class for this association will enhance the structure. You got this! 🌟👩‍💻 #CodeImprovement #KeepCoding #CodeReviewFeedback 🙏🏼

### A person has many rentals
## EXAMPLE:

```ruby
  # *A method for adding rentals should be present. Link to the example in a previous lesson: https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship
  def add_rental(book, date)
    # *The person itself should be sent as a parameter to create the new rental achieving the 'has-many' association
    Rental.new(date, book, self)
  end
```

2023-12-02 11:44 UTC, skyv26 approved these changes
## Hi @FilbertKimasa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWRlYTU0OTIzYTBiYTA3Yjg4ZjNhNDY3MWE3ZDgzOWE1NjA5ZWNiMiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/JM8GJXq9HvMPZjQfng/giphy.gif)

## Highlights
- Implemented the features asked by the previous code reviewer ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 11:57 UTC, merged